version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cvats-backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    restart: always

  redis:
    image: redis:7
    container_name: cvats-redis
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cvats-celery
    command: celery -A core.celery_config worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cvats-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
